<a href="https://colab.research.google.com/github/sinayavarian/AI-Development/blob/main/Lab_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 1 </p>

In [1]:
# importing numpy
import numpy as np

In [3]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
arr = np.array([1, 2, 3, 5, 0])
print(arr)
print(np.all(arr))

[1 2 3 5 0]
False


In [5]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.
arr = np.array([3, -1, 3, 7, 2])
print(arr)
print(np.any(arr))

[ 3 -1  3  7  0]
True


In [6]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.
arr = np.array([0, 0, 0, 0])
print(arr)
print(np.any(arr))

[0 0 0 0]
False


In [7]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.
arr = np.array([56, -2, 7])
print(arr)
print(arr.nbytes)

[56 -2  7]
24


In [9]:
# Create a numpy array with 10 zeros and print the array.
arr = np.zeros(10)
print(arr)


# Create a numpy array with 6 ones and print the array.
arr = np.ones(6)
print(arr)

# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
arr = np.full(12, 3)
print(arr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[3 3 3 3 3 3 3 3 3 3 3 3]


In [11]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
arr = np.arange(8, 21)
print(arr)

# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method
arr = np.arange(8, 21, 2)
print(arr)


[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 8 10 12 14 16 18 20]


In [14]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
arr = np.random.normal(2, 0.5, 100)
print("100 numbers mean: ", np.mean(arr))
print("100 numbers max: ", np.max(arr))
print("100 numbers min: ", np.min(arr))
print("100 numbers std: ", np.std(arr))

# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
arr = np.random.normal(2, 0.5, 1000)
print("1000 numbers mean: ", np.mean(arr))
print("1000 numbers max: ", np.max(arr))
print("1000 numbers min: ", np.min(arr))
print("1000 numbers std: ", np.std(arr))


# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
arr = np.random.normal(2, 0.5, 1000000)
print("1000000 numbers mean: ", np.mean(arr))
print("1000000 numbers max: ", np.max(arr))
print("1000000 numbers min: ", np.min(arr))
print("1000000 numbers std: ", np.std(arr))

# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?



100 numbers mean:  1.9775133717780218
100 numbers max:  3.53680661384288
100 numbers min:  0.8131778575684492
100 numbers std:  0.528394207108277
1000 numbers mean:  2.0004993892732155
1000 numbers max:  3.781429880108728
1000 numbers min:  0.4477979129774836
1000 numbers std:  0.5049821228228468
1000000 numbers mean:  1.9998226048760406
1000000 numbers max:  4.600924886494477
1000000 numbers min:  -0.4128730220804928
1000000 numbers std:  0.49999022495204964
