<a href="https://colab.research.google.com/github/sinayavarian/Math-for-AI/blob/main/Lab_Exercise_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 8</p>

In [10]:
# Import the built-in iris dataset to work with
iris = datasets.load_iris() # the dataset consists of 3 different types of irises' (Setosa, Versicolour, and Virginica) petal and sepal length
print("iris dataset",iris.data[:10,:])
X = iris.data[:, :2] # We only want to use the first two features (Sepal Length, Sepal Width)
y = iris.target # corresponding to 'setosa', 'versicolor', 'virginica
print("iris target",y[:10,])

iris dataset [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
iris target [0 0 0 0 0 0 0 0 0 0]


In [9]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets

In [ ]:
# Develop a linear Support Vector Machine to classify the irises
# Use GridSearchCV to optimize the model's hyperparameters (C, gamma, kernel)
# Compare the accuracies of the above two models

In [64]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [65]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
linear_model = SVC(C= 10, gamma= 1, kernel="linear", random_state = 42)

linear_model.fit(X_train, y_train)
y_pred_linear = linear_model.predict(X_test)
acc_linear = accuracy_score(y_test, y_pred_linear)

print("Model 1 - Linear SVM accuracy:", acc_linear)


Model 1 - Linear SVM accuracy: 0.8421052631578947


In [66]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['linear'], 'random_state': [42]}
grid = GridSearchCV(
    SVC(),
    param_grid,
    refit=True,
    verbose=3
)
grid.fit(X_train, y_train)


Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END C=0.1, gamma=1, kernel=linear, random_state=42;, score=0.783 total time=   0.0s
[CV 2/5] END C=0.1, gamma=1, kernel=linear, random_state=42;, score=0.696 total time=   0.0s
[CV 3/5] END C=0.1, gamma=1, kernel=linear, random_state=42;, score=0.864 total time=   0.0s
[CV 4/5] END C=0.1, gamma=1, kernel=linear, random_state=42;, score=0.864 total time=   0.0s
[CV 5/5] END C=0.1, gamma=1, kernel=linear, random_state=42;, score=0.727 total time=   0.0s
[CV 1/5] END C=0.1, gamma=0.1, kernel=linear, random_state=42;, score=0.783 total time=   0.0s
[CV 2/5] END C=0.1, gamma=0.1, kernel=linear, random_state=42;, score=0.696 total time=   0.0s
[CV 3/5] END C=0.1, gamma=0.1, kernel=linear, random_state=42;, score=0.864 total time=   0.0s
[CV 4/5] END C=0.1, gamma=0.1, kernel=linear, random_state=42;, score=0.864 total time=   0.0s
[CV 5/5] END C=0.1, gamma=0.1, kernel=linear, random_state=42;, score=0.727 total time=   0.0

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear'], 'random_state': [42]},
             verbose=3)

In [67]:
best_model = grid.best_estimator_

y_pred_best = best_model.predict(X_test)
acc_best = accuracy_score(y_test, y_pred_best)
print("\nModel 2 - GridSearch Best accuracy:", acc_best)
print("Best params:", grid.best_params_)


Model 2 - GridSearch Best accuracy: 0.8421052631578947
Best params: {'C': 1, 'gamma': 1, 'kernel': 'linear', 'random_state': 42}


In [68]:
print("Model 1 - Linear SVM accuracy:", acc_linear)


Model 1 - Linear SVM accuracy: 0.8421052631578947


In [69]:
print(confusion_matrix(y_test, y_pred_linear))

[[15  0  0]
 [ 0  7  4]
 [ 0  2 10]]


In [70]:
print(confusion_matrix(y_test, y_pred_best))

[[15  0  0]
 [ 0  7  4]
 [ 0  2 10]]
